sudo: required

language: java
jdk:
- oraclejdk8

services:
  - mongodb
  - docker

before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

after_success:
- mvn test jacoco:report
- java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r /home/travis/build/ushandelucca/MeasurementServer/target/site/jacoco/jacoco.xml
- if [ "$TRAVIS_BRANCH" == "master" ]; then
     mvn clean package;
     docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
     docker build . -t oo2a/tankserver;
     docker push oo2a/tankserver;
     fi