version: "3"
services:
  mongodb:
    image: mongo:5.0
    container_name: mongo
    volumes:
      - ./configdb:/data/configdb
      - ./db:/data/db
    ports:
      - 27017:27017

  mongoexpress:
    image: mongo-express
    container_name: mongoexpress
    ports:
      - 8081:8081
