name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Git checkout
        uses: actions/checkout@v2

      # Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      # Start a MongoDB for the test
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: '4.4'

      # Maven build
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      # Docker build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Login to DOCKERHUB
      - name: Login to DOCKERHUB
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build and push to DOCKERHUB
      - name: Build and push to DOCKERHUB
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: oo2a/measurement-server:latest
