name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Git checkout
        uses: actions/checkout@v4

      # Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      # Start a MongoDB for the test
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: 5.0

      # Maven build
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Set Release version env variable
        run: echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      # Docker build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to DOCKERHUB
      - name: Login to DOCKERHUB
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build and push to DOCKERHUB
      - name: Build and push to DOCKERHUB
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: oo2a/measurement-server:${{ env.RELEASE_VERSION }},oo2a/measurement-server:latest
